spring:
  datasource:
    schema: classpath:/org/springframework/social/connect/jdbc/JdbcUsersConnectionRepository.sql
  security:
    social: 
      implicit-singup: false 
  thymeleaf:
    cache: false

facebook:
  clientId: 568259723364175
  clientSecret: 8fa26e8b1cf1374cf030a80ca2c568b2

google:
  clientId: 157930201267-9946d8c252jvntt6jgvujra3mdfnbvnq.apps.googleusercontent.com
  clientSecret: 81U3TAlw3TQf8bRnLQtSgFdb

logging:
  level:
    org.springframework:
      security: DEBUG
      social: DEBUG
      
